### ISSUE TITLE
val rec式に 多相な型のアノテーションを付けるとエラーになる

### ISSUE THREAD

**Issue by eldesh** [smlsharp/smlsharp#10]
以下のように、再帰したval宣言(?)に多相な型のアノテーションを付けるとコンパイルエラーとなります。
多相でなく(例えばint list -> int)を指定するとエラーは出なくなります。
また、アノテーションを付けない場合もエラーは出なくなり、その場合は多相型が正しく推論されます。

``` sml
(* bar.sml *)
val rec sizeL : 'a list -> int = fn xs =>
    case xs
      of [] => 0
       | _::xs => 1 + sizeL xs
```

コンパイルするとエラーになる。

``` sh
$ smlsharp bar.sml
[BUG] EvalITy: free tvar:'a
```

**Comment by yonta** [comment]
v3.6.0でも再現

**Comment by uenoB** [comment]
これはバグです。修正しました。

**Comment by eldesh** [comment]
私の手元では再現するようです…？

```smlsharp
SML# 4.0.0 (2021-04-06 05:12:50 JST) for x86_64-unknown-linux-gnu with LLVM 9.0.0
# val rec sizeL : 'a list -> int = fn xs =>
>     case xs
>       of [] => 0
>        | _::xs => 1 + sizeL xs;
Bug.Bug: EvalITy: free tvar:'a(tv5378) at src/compiler/compilerIRs/idcalc/main/EvalIty.sml:14.14(258)
```

**Comment by KeenS** [comment]
このコミットで修正されているようなのでmaster版で直っているんじゃないでしょうか。
https://github.com/smlsharp/smlsharp/commit/0b8a9f238e8942b5e74ac0d749a30296ad350ebc

**Comment by uenoB** [comment]
はい、master版をお試しください。
うまくビルドできているとバージョン番号が`4.0.1-2.g0b8a9f23`みたいな形になるはずです。

**Comment by eldesh** [comment]
4.0.1-6.g471c96c3 で修正を確認しました。
