### ISSUE TITLE
basis.smiが提供するものと同名の関数を定義するとバグが起きる

### ISSUE THREAD

**Issue by eldesh** [smlsharp/smlsharp#29]
以下のように _basis.smi_ で提供される _structure Word_ の提供する関数と同名の関数を定義すると、コンパイル時にバグとして報告される。
## 再現コード

``` sml
(* w.sml *)
structure Word =
struct
  type t = Word.word
  val wordSize = Word.wordSize
end
```

``` sml
(* w.smi *)
 _require "basis.smi"
structure Word =
struct
  type t = Word.word
  val wordSize: int
end
```
## エラー

``` sh
$ smlsharp w.sml
uncaught exception: Bug.Bug: defineTopdecs: duplicated top symbol _SMLN4Word8wordSizeE at src/compiler/llvmemit/main/LLVMEmit.sml:688
```
## 備考

このエラーはsmiファイルから該当する名前が公開される場合のみ発生し、replから _use_ した場合は発生しない。
また、他のstructureが提供する関数でもstructure名まで含めた名前が重複すれば同様にエラーとなる。

似たようなケースとして、ユーザ定義のstructure名同士が重複した場合は _duplicate structure name_ エラーとなる。 (これは少し回りくどいが #19 のコードで再現出来る)

**Comment by yonta** [comment]
v3.6.0からはBugでなく同名ストラクチャのエラーになった
```sml
W.smi:2.10-2.13 Error:
  (name evaluation "207v") duplicate structure name: Word
```

**Comment by eldesh** [comment]
継続されないなら閉じますね
