### ISSUE TITLE
フィードバックが欲しい

### ISSUE THREAD

**Issue by KeenS** [smlsharp/smlsharp#34]
メタな話。ここに挙がっているバグが上流で修正されたのかのフィードバックが欲しいです。
いくつかのバグ(例えば [これとか](https://github.com/smlsharp/smlsharp/issues/30))はメッセージ読んで周辺コードを見れば私でも直せそうですがそういうものは既に上流では直ってそうなのでイシューを閉じるかコメントをつけるかして頂ければパッチを投げ易くなります。

**Comment by KeenS** [comment]
理想的には開発プロセスもオープンにして頂ければこちらとしては嬉しいのですがそこは開発ポリシーに係るのでそこまでは。

**Comment by uenoB** [comment]
このリポジトリが公式リポジトリになり、開発もこのリポジトリを使って行うことになりました。これからはどんどんフィードバックしていきます。今後ともよろしくお願いいたします。
