### ISSUE TITLE
OS.Path.mkCanonicalを日本語を含む文字列に対して呼ぶとエラーになる

### ISSUE THREAD

**Issue by KeenS** [smlsharp/smlsharp#39]
SMLが文字列にASCIIしか想定してないのでバグなのか仕様なのか判断つかないのですが実用上困るのでwantfixということで。

再現コード

``` sml
(* run.sml *)
val _ = OS.Path.mkCanonical "/ユーザ情報"
```

``` sml
(* run.smi *)
_require "basis.smi"
```

``` sh
$ smlsharp -o run run.sml
$ ./run
uncaught exception: InvalidArc
$ smlsharp <<EOF
heredoc> OS.Path.mkCanonical "/ユーザ情報"
heredoc> EOF
SML# 2.0.0 (2014-04-04 11:47:08 JST) for i686-apple-darwin14.3.0 with LLVM 3.4
# > uncaught exception InvalidArc at src/smlnj/Basis/OS/os-path-fn.sml:56
```

因みにSML/NJではエラーになりません。MLtonだとこのコードのコンパイルは日本語を含むのでエラーになりますが `OS.FileSys.openDir`で `"/"`を開いて
`"/ユーザ情報"` を含む全てのディレクトリに`mkCanonical`を適用してもエラーになりません。

**Comment by KeenS** [comment]
smlsharp-3.0.0でも同じなので引き続きwantfix

**Comment by KeenS** [comment]
smlsharp-3.3.0にて再現確認

**Comment by yonta** [comment]
以前はWideCharというモジュールで対応していたんですが、いつの間にかなくなっていました。

**Comment by yonta** [comment]
v3.6.0でも同じ

**Comment by uenoB** [comment]
修正しました。このバグはSML/NJ 110.74に由来します。110.75で修正されていたようなので、110.75での修正をそのまま取り込みました。

**Comment by KeenS** [comment]
ありがとうございます。
