### ISSUE TITLE
[機能要望] [FFI] unit ptrとSMLの型の相互運用

### ISSUE THREAD

**Issue by KeenS** [smlsharp/smlsharp#45]
# 問題

Cでは、多相型の代わりとして`void *`を使うことがありますが、それをSML#で使おうとした時にSML＃の値を渡せなくて困ることがあります。

例えば`int pthread_create(pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine) (void *), void *arg)`の例だとSMLにインポートする時に

``` sml
val pthread_create = _import "pthread_create" : (pthread_t ref,  pthread_attr_t ref, unit ptr -> unit ptr, unit ptr) -> int
```

となりますが、unit ptrにSMLの型を渡せないので事実上第4引数の`arg`には何も渡せません。あるいは`pthread_join`も本来ならcreateの時に作った関数の返り値を受け取れる筈ですが、同様の理由で事実上何も受け取れません。
# 提案
- Cとの相互運用型について、`toUnitPointer`と`fromUnitPointer`を実装する
- オーバーロードでそれらの関数を一纏めに扱えるようにする
- 実体はただのキャスト
- `unit ptr`型については幽霊型で型付けをして、型安全性を壊さないようにする
## 例

``` sml
type pthread_t = unit ptr
type pthread_attr_t = unit ptr
val pthread_create = _import "pthread_create" : (pthread_t ref, pthread_attr_t ref, 'a unit ptr -> 'b unit ptr, 'a unit ptr) -> int
val pthread_join = _import "pthread_join": (pthread_t, 'a unit ptr ref) -> int

(* val threadFunc: string unit ptr -> int unit ptr *)
fun threadFunc arg  = let
    val s = fromUnitPtr arg
    val () = print s
    val ret = (String.size s)
in
    toUnitPtr ret
end

val () = let
    val thread_ref: pthread_t ref = ref _NULL
    val attr_ref: pthread_attr_t ref = ref _NULL 
    val s = pthread_create(thread_ref, attr_ref, threadFunc, toUnitPointer "Hello, World\n")
    val t1 = !thread_ref
    val () = if s <> 0
             then OS.Process.exit OS.Process.failure
             else ()
    val () = print "Message from main()\n";
    val resRef: int unit ptr ref = ref _NULL
    val s = pthread_join(t1, resRef)
    val () = if s <> 0
             then OS.Process.exit OS.Process.failure
             else ()
    val () = print ("Thread returned" ^ Int.toString  (fromUnitPointer (!resRef)) ^ "\n")
in
    ()
end
```

この例ではあまり無理のないようにしましたがやろうと思えば`pthread_t`型にも幽霊型を付ければ`pthread_join`も正しく型付け出来る筈です。
## 細かい部分
- (C言語的には未規定動作ですが) intに対して`toUnitPtr`を呼ぶと`int unit ptr`になり、`int ptr`などにはならない。つまり、intのポインタを取るのではなく、intをそのまま(void *)にキャストする。
- refも同じく。つまり、`int ref`を`toUnitPtr`するのはCでいえば`int *`を`void *`にキャストするのと同じ。

SML#のC FFIはすごい面白い機能だと思っているのですが微妙にかゆいところに手が届かないので要望を上げさせて頂きました。型システムにどこまで影響するのか分かってないのですが可能そうなら実現していただけると幸いです。

**Comment by uenoB** [comment]
多相FFIを使ってください。Cの`void*`がパラメトリック多相的に振る舞うなら（値のコピーとかしかしないなら）、`'a#boxed`で`void*`としてCに渡せるSML#の型を総称できます。
```sml
val 'a#boxed pthread_create =
    _import "pthread_create"
    : (pthread_t ref, unit ptr, 'a -> unit ptr, 'a) -> int
```

**Comment by KeenS** [comment]
`'a#boxed` で事足りそうです。ありがとうございます。
