### ISSUE TITLE
sml# build failure from source - and a fix.

### ISSUE THREAD

**Issue by basabuber** [smlsharp/smlsharp#51]
Following the build instructions for building from source, I encountered the following error:

...
/usr/bin/xz -c -d ./precompiled/x86_64.ll.xz \
| /home/miki/local/llvm/bin/llvm-as -o precompiled/x86_64.bc
{ echo 'VERSION = '`cat VERSION`; \
  echo 'RELEASE_DATE = '`cat RELEASE_DATE`; \
  echo 'LIBDIR_SMLSHARP = /home/miki/local/sml/lib/smlsharp'; \
  cat src/config.mk; \
  sed -n '/^SIZEOF_VOID_P/p' config.mk; } \
| sed 's/["\\]/\\\\\\&/g;s/^/s"%/;s/ = /%"/;s/$/";/' > src/config.sed
rm -f src/runtime/libsmlsharp.a
ar qc src/runtime/libsmlsharp.a src/runtime/callback.o src/runtime/control.o src/runtime/error.o src/runtime/exn.o src/runtime/finalize.o src/runtime/init.o src/runtime/object.o src/runtime/xmalloc.o src/runtime/prim.o src/runtime/splay.o src/runtime/top.o src/runtime/dump.o src/runtime/livecheck.o src/runtime/netlib/dtoa.o src/runtime/heap_concurrent.o src/sql/main/builtintypes/timestamp/string_to_time_t.o src/sql/main/builtintypes/timestamp/timeval_to_string.o
ranlib src/runtime/libsmlsharp.a
sed -f src/config.sed ./src/config/main/Version.sml.in > src/config/main/Version.sml
sed -f src/config.sed ./src/config/main/PointerSize.sml.in > src/config/main/PointerSize.sml
g++ -shared -o src/llvm/smlsharp_gc.so src/llvm/main/smlsharp_gc.o
/home/miki/local/llvm/bin/llc -load=src/llvm/smlsharp_gc.so -mtriple=x86_64-pc-linux-gnu -O2 \
-tailcallopt -filetype=obj -o precompiled/x86_64.o precompiled/x86_64.bc
g++  -L/home/miki/local/llvm/lib  -Wl,-rpath,'/home/miki/local/llvm/lib' \
precompiled/x86_64.o \
src/llvm/main/llvm_support.o src/runtime/main.o src/runtime/libsmlsharp.a \
-lLLVM-3.7 -lz -lpthread -ltinfo -ldl -lm  -lpthread -lyajl -ldl -lgmp -lm  -o minismlsharp
/usr/bin/ld: precompiled/x86_64.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:224: recipe for target 'minismlsharp' failed
make: *** [minismlsharp] Error 1

---

The fix was to resume the build with:

/home/miki/local/llvm/bin/llc -relocation-model=pic -load=src/llvm/smlsharp_gc.so -mtriple=x86_64-pc-linux-gnu -O2 -tailcallopt -filetype=obj -o precompiled/x86_64.o precompiled/x86_64.bc

g++  -L/home/miki/local/llvm/lib  -Wl,-rpath,'/home/miki/local/llvm/lib' precompiled/x86_64.o src/llvm/main/llvm_support.o src/runtime/main.o src/runtime/libsmlsharp.a -lLLVM-3.7 -lz -lpthread -ltinfo -ldl -lm  -lpthread -lyajl -ldl -lgmp -lm  -o minismlsharp

---

Could you add the '-relocation-model=pic' flag to the llc invocation?

Thanks!

**Comment by yonta** [comment]
Thanks to report.

The same error is occurred in SML# v3.0.0.
Official team has recgnized this error.
Please, wait for fix in next version.

> https://twitter.com/smlsharp/status/717001511297875969

**Comment by yonta** [comment]
From SML# version 3.5.0, there is setting of `LLCFLAGS`, that is `LLCFLAGS="$LLCFLAGS -relocation-model=pic"`.
