### ISSUE TITLE
Building from source: 'error-expected-type' in precompiled bc

### ISSUE THREAD

**Issue by mmaul** [smlsharp/smlsharp#52]
I suspect this might be related to differences in llvm versions even though I am  llvm-3.7.1. Is it possible to rebuild the precompiled section?

Output below
`/usr/bin/xz -c -d ./precompiled/x86_64.ll.xz \
> | /usr/bin/llvm-as -o precompiled/x86_64.bc
/usr/bin/llvm-as: <stdin>:24331:39: error: expected type
@_SMLZN4Time8zeroTimeE=internal alias getelementptr inbounds(<{[4x i8],i32,[8x i8*]}>,<{[4x i8],i32,[8x i8*]}>*@_SML_gvr.64,i64 0,i32 2,i64 0)
                                      ^
[localhost smlsharp]$ uname -a
Linux localhost.localdomain 4.8.6-300.fc25.x86_64 #1 SMP Tue Nov 1 12:36:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[localhost smlsharp]$ man llvm-config
[localhost smlsharp]$ llvm-config --version
3.7.1
[localhost smlsharp]$ cat /etc/fedora-release 
Fedora release 25 (Twenty Five)
`

**Comment by yonta** [comment]
Now, SML# compiler supports Fedora OS by rpm package.
Please, try it.

https://www.pllab.riec.tohoku.ac.jp/smlsharp/?Download
