### ISSUE TITLE
Compiler does not raise overflow exception in Interger

### ISSUE THREAD

**Issue by yonta** [smlsharp/smlsharp#59]
In integer addition that cause overflow of 32 bit integer, SML# compiler does not raise overflow exception.
In basis library, It is written that 'They raise Overflow when the result is not representable. '.

I think that whether integer overflow is representable or not is controversial.
I can not decide that it is bug or not.

```sml
(* overflow.sml *)
(* _require "basis.smi" *)
val () = print (Int.toString (Int.maxInt + 1))
```

```shell-session
$ smlsharp overflow.sml
$ ./a.out
~2147483648
```

**Comment by KeenS** [comment]
same as #1 ?

**Comment by yonta** [comment]
Yes, I see.
