### ISSUE TITLE
The document of 'プログラミング言語SML#解説' has invalid link

### ISSUE THREAD

**Issue by yonta** [smlsharp/smlsharp#63]
The Japanese document has links to `https://www.pllab.riec.tohoku.ac.jp/smlsharp/docs/3.6.0/ja/` in top of `Part N` pages.
For example, in [this page](https://www.pllab.riec.tohoku.ac.jp/smlsharp/docs/3.6.0/ja/Pt2.xhtml).

But now, this link will lead to 403 forbidden error page.
Because this link does not redirect to `https://www.pllab.riec.tohoku.ac.jp/smlsharp/docs/3.6.0/ja/index.xhtml`.

[Link](https://www.pllab.riec.tohoku.ac.jp/smlsharp/docs/3.6.0/ja/)

**Comment by uenoB** [comment]
Fixed. Thanks!
