### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by MichelBoucey** [smlsharp/smlsharp#64]
Hi,

I try to compile `smlsharp-4.0.0` on ArchLinux, but `./configure` stops on this error :

```
checking whether isnormal is declared... yes
checking whether signbit is declared... yes
checking for max_align_t... yes
checking size of int... 0
configure: error: required type int is not found.
```

**Comment by uenoB** [comment]
I guess that you have installed MassiveThreads in `/usr/local` and you have not added `/usr/local/lib` to the library path. If so, could you try to run the following commands to enable `/usr/local/lib` and run `./configure` again?
```
echo '/usr/local/lib' > /etc/ld.so.conf.d/usrlocal.conf
ldconfig
```

**Comment by MichelBoucey** [comment]
Thanks... I didn't see that MassiveThreads library wasn't installed on a non standard library path.
