### ISSUE TITLE
Can it be built with GCC, without LLVM?

### ISSUE THREAD

**Issue by barracuda156** [smlsharp/smlsharp#76]
LLVM is broken for some platforms. Is it required, or SML# can be bootstrapped with GCC?

**Comment by t18b219k** [comment]
No you can't bootstrap using gcc.
make will unpack precompiled.ll.xz and compile precompiled.ll using llc.
The compiled artifact will compile stage2 compiler.
Therefore we need llvm 14 or earlier.

**Comment by barracuda156** [comment]
> make will unpack precompiled/x86_64.ll.xz and compile precompiled/x86_64.ll using llc.

This is even worse than I thought. If so, even fixing LLVM won’t help, it is essentially hardcoded for Intel.
